- Add USB Host kernel config, scripts and docs - Polish first_login script - Add some packages for gstreamer

diff --git a/rootfs_overlay/etc/init.d/S49gether b/rootfs_overlay/etc/init.d/S49gether
--- a/rootfs_overlay/etc/init.d/S49gether
+++ b/rootfs_overlay/etc/init.d/S49gether
@@ -9,26 +9,33 @@ mkdir -p /run/network
 
 case "$1" in
   start)
-        printf "Starting g_ether: "
-        /sbin/modprobe g_ether
-        /sbin/ip address add dev usb0 172.16.42.2/24
-        /sbin/ip link set usb0 up
-        sleep 3s
-        /sbin/ip route add default via 172.16.42.1 dev usb0
-        [ $? = 0 ] && echo "OK" || echo "FAIL"
-        ;;
+    if [[ -z $( ip address | grep inet ) ]]
+    then
+      echo device > /sys/class/usb_role/ffe09000.usb-role-switch/role
+      printf "Starting g_ether: "
+      modprobe g_ether
+      ip address add dev usb0 172.16.42.2/24
+      ip link set usb0 up
+      sleep 3s
+      ip route add default via 172.16.42.1 dev usb0
+      [ $? = 0 ] && echo "OK" || echo "FAIL"
+    fi
+    ;;
   stop)
-        printf "Stopping g_ether: "
-        /sbin/modprobe -r g_ether
-        [ $? = 0 ] && echo "OK" || echo "FAIL"
-        ;;
+    printf "Stopping g_ether: "
+    if [[ ! -z $( lsmod | grep g_ether ) ]]
+    then
+      modprobe -r g_ether
+    fi
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
   restart|reload)
-        "$0" stop
-        "$0" start
-        ;;
+    "$0" stop
+    "$0" start
+    ;;
   *)
-        echo "Usage: $0 {start|stop|restart}"
-        exit 1
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 esac
 
 exit $?
